import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import TopStrip from './components/Navbar/TopStrip';

export const metadata = {
  title: 'GrapesGenix',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="assets/favico.jpg" />
      </head>
      <body>
        <TopStrip />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
